### ISSUE TITLE
dbus-pcap: struct.error: unpack requires a bytes object of length 1

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-tools#50]
Ran into this when trying out the tool to parse a pcap file. 

```
 python3 ~/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap ~/delete-me/good.pcap
....
[[[108, 4, 1, 1, 11, 4294967295], [[7, "org.freedesktop.DBus"], [6, ":1.116"], [1, "/org/freedesktop/DBus"], [2, "org.freedesktop.DBus"], [3, "NameAcquired"], [8, "s"]]], [":1.116"]]
[[[108, 1, 0, 1, 117, 2], [[1, "/org/freedesktop/DBus"], [3, "AddMatch"], [2, "org.freedesktop.DBus"], [6, "org.freedesktop.DBus"], [8, "s"], [7, ":1.116"]]], ["type='signal',member='JobRemoved',path='/org/freedesktop/systemd1',interface='org.freedesktop.systemd1.Manager',"]]
unpack requires a bytes object of length 1
parse_fixed: Error unpacking b''
parse_fixed: Attempting to unpack type DBusType.BYTE with properties TypeProperty(field=<DBusType.BYTE: 121>, type='B', nature=1)
AlignedStream: absolute offset: 81
AlignedStream: relative offset: 69
RawMessage(endian=108, header=b'l\x02\x01\x01\x00\x00\x00\x00\xff\xff\xff\xff', data=b'>\x00\x00\x00\x05\x01u\x00\x02\x00\x00\x00\x07\x01s\x00\x14\x00\x00\x00org.freedesktop.DBus\x00\x00\x00\x00\x06\x01s\x00\x06\x00\x00\x00:1.116\x00\x00\x08\x01g\x00\x00\x00\x00\x00')
Traceback (most recent call last):
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 206, in parse_fixed
    val = struct.unpack("{}{}".format(endian, prop.type), val)[0]
struct.error: unpack requires a bytes object of length 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 400, in <module>
    main()
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 394, in main
    for msg in parse_session(stream, matchers):
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 338, in parse_session
    cooked = parse_packet(packet)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 332, in parse_packet
    msg = parse_message(RawMessage(data[0], data[:12], data[12:]))
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 328, in parse_message
    raise e
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 319, in parse_message
    header, data = parse_header(raw)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 294, in parse_header
    fields = parse_fields(endian, astream)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 280, in parse_fields
    fields = parse_container(endian, stream, sig)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 270, in parse_container
    return parse_array(endian, stream, tc.members)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 252, in parse_array
    elem = parse_type(endian, stream, tc)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 240, in parse_type
    val = parse_container(endian, stream, tc)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 272, in parse_container
    return parse_struct(endian, stream, tc.members)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 260, in parse_struct
    arr.append(parse_type(endian, stream, tc))
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 236, in parse_type
    val = parse_fixed(endian, stream, tc)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 212, in parse_fixed
    stream.dump_assert(False)
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 198, in dump_assert
    self.dump()
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 192, in dump
    print("AlignedStream: remaining buffer:\n{}".format(self.drain()[0]))
  File "/Users/andrewg/Code/openbmc-tools/amboar/obmc-scripts/dbus-pcap/dbus-pcap", line 186, in drain
    assert self.offset - self.stash[1] == len(self.stash[0])
AssertionError
```

**Comment by geissonator** [comment]
Doesn't look like github supports pcap file formats. Let me know if you want to take a look at it @amboar . I didn't dig into this one very much.

**Comment by amboar** [comment]
Can you zip/tar.gz it and upload please?

**Comment by geissonator** [comment]
[good.pcap.zip](https://github.com/openbmc/openbmc-tools/files/3069221/good.pcap.zip)

**Comment by amboar** [comment]
Fixed by https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-tools/+/20524
